# Generated by Django 3.2.5 on 2023-11-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labname', models.CharField(max_length=100)),
                ('labbudget', models.IntegerField()),
            ],
            options={
                'permissions': [('view_labs', 'can view lab details')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('refno', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
